### ISSUE TITLE
Feature Request: Filter by duration

### ISSUE THREAD

**Issue by mihalski** [royto/logbook-card#29] opened 2020-05-26 10:02 UTC
First of all thank you for a very useful card.

Would it be possible to add a feature where entries with a duration shorter than a certain time are ignored?

In my case this would be useful when entering zones. Sometimes you get 16s of time in a zone before you leave it and then enter it again for real. Other times you drives PAST something without stopping there and get listed as being at a location for 2s.

Come to think of it it might be nice to be able to collapse two adjacent events together if the interim event was shorter than a certain period of time (ie. "away" for a minute between being at the same place again). This seems like a more difficult problem to solve however.

Thank you again!

**Comment by royto** [comment] 2020-05-26 11:05
Thank you for your support.

I add this in my feature list to implement :wink:

I already a case where a merge state if state is hidden. So it could be possible. Maybe as an option ...

**Comment by xvolte** [comment] 2020-08-06 23:01
Hello,
i also needed to hide with the hidden feature, when the sensors are "unavailable".
Usually, it happens for less than 2 minutes...
Than i got a lot of "Door Closed" displayed, where i would only need "One" that would be the sum of all the minutes spent, unless i get a "Door Open" event...

Would that be possible ?

two screenshot to explain myself

Without filter:
![withoutfilter-logcard](https://user-images.githubusercontent.com/21142611/89590966-53e5c200-d849-11ea-8d3c-c91bdd92b4d0.png)

With filter:
![withfilter-logcard](https://user-images.githubusercontent.com/21142611/89590979-59dba300-d849-11ea-84a0-c7bcdead653e.png)


what i would need is a single entry "Fermé" with the sum of all minutes of the past events "Fermé" before an "Ouvert" state

**Comment by royto** [comment] 2022-12-06 20:59
Hi, 
I'm working back on the card to fix/upgrade some stuff right now.
I'll try to implement this. 
I assume that this is some globally not not limited to some state ...
i thinking about having a `minimal_duration` option configured in seconds. What do you think ?

**Comment by cdk222** [comment] 2022-12-07 14:18
I think a minimal_duration duration in seconds is defiantly the way to go. Allows users to cut out the noise when controllers drop wifi, or something (power reset) that turns them on-off. 

Below is the noise I would like to remove:

![image](https://user-images.githubusercontent.com/45811133/206202611-3b760689-6ab1-4e9d-8f9b-1982107d832f.png)

Also thanks for being so responsive

**Comment by royto** [comment] 2022-12-08 07:09
I assume you want all events to be squashed together right ? If same state before and after ...

**Comment by cdk222** [comment] 2022-12-09 14:04
In my config I am ignoring "off" and "unavailable" so they are not shown in the above example. Not sure I understand " If same state before and after ..."

**Comment by hubikj** [comment] 2022-12-09 15:19
I think that an option to "merge across unavailable" would be best. Maybe with an option on max duration of unavailable beyond which the merge would not take place.

**Comment by royto** [comment] 2022-12-09 16:30
If your entity can have multiple states (not just on/off) you don't want to merge them ...

for example:
``` 
state1 -> duration: 10m
state2 -> duration: 2s
state3 -> duration: 5m
``` 

if you have minimal duration to 10s you want to have as a result
```
state1 -> duration: 10m
state3 -> duration: 5m
```

but if it goes back to the previous state 
```
on-> duration: 10m
off -> duration: 2s
on -> duration: 5m
``` 

some may want 
```
 on-> duration: 10m 
 on -> duration: 5m
``` 

and others
`on -> duration: 15m`

**Comment by cdk222** [comment] 2022-12-09 16:51
I see what you are saying. 
For example 1 and 3, I think it depends on how you use the hiddenState variable.
Im not sure how you would tie a minDuration to a particular state
For example 5 you could introduce  variable "mergeDuration" (true/false) 

I can only speak for myself but my use case would be:
```
minDuration: 10s
hiddenState:
   - state2
   - unavailable
   
state1 -> duration: 10m
state1 -> duration: 5m
```

**Comment by hubikj** [comment] 2022-12-09 18:27
@cdk222's use case would not solve @xvolte's problem. That problem is caused by brief periods of unavailability and it makes logbooks very annoying to read. Instead of one long period for a state you have it chopped up by the `unavailable` states. My idea was this:

```
mergeUnavailable: true
maxMergeUnavailableGapDuration: 60s
hiddenState:
   - off
   - unavailable
```
And then
```
on -> duration: 10m
off -> duration: 2s
on -> duration: 5m
```
Would give
```
on -> duration: 10m
on -> duration: 5m
```
But
```
on -> duration: 10m
unavailable -> duration: 2s
on -> duration: 5m
```
Would give
```
on -> duration: 15m2s
```
But
```
on -> duration: 10m
unavailable -> duration: 61s
on -> duration: 5m
```
Would give
```
on -> duration: 10m
on -> duration: 5m
```
And
```
on -> duration: 10m
off -> duration: 1s
unavailable -> duration: 1s
on -> duration: 5m
```
Would also give
```
on -> duration: 10m
on -> duration: 5m
```
Because the states were not the same (essentially the same as first example - the added unavailable does not matter in this case).

This could also be combined with additional filtering for minDuration, but then I would suggest to do merging first and then filter based on min duration. Otherwise things might disappear just because a sensor has bad WiFi signal and drops frequently.

**Comment by royto** [comment] 2022-12-11 20:49
I wondering if this should be configured per state and not not only for unavailable ...

i would fix @mihalski requests ... but it is a litlle be more work

**Comment by cdk222** [comment] 2022-12-12 14:16
hmmm Id agree with per state for the increased flexibility

**Comment by adamburgoyne** [comment] 2023-05-25 12:48
I don't suppose this ever went anywhere or if there's a solution to  _"I think a minimal_duration duration in seconds is defiantly the way to go."_ ?

I have a few automations that involve our robot vacuum going to the bin to be emptied which shows up as 30 seconds vs the normal 20 minute runtimes. I've filtered out states that I don't want which has been a big help but ideally I also want to exclude anything under 1 minute from the results but I can't seem to find a way to do that at the moment.

**Comment by royto** [comment] 2023-06-05 19:57
New version 1.11.0 add `minimal_duration` config allowing to filter entry less than a certain duration (entry will be squash if previous and next entry has same state)

**Comment by philhzss** [comment] 2023-08-20 23:38
> New version 1.11.0 add `minimal_duration` config allowing to filter entry less than a certain duration (entry will be squash if previous and next entry has same state)

Hey, just wanted to say thank you!! I was looking for exactly this, found this thread, assumed the feature wasn't implemented yet because the issue was still open, but this works perfectly! Thank you

**Comment by royto** [comment] 2023-08-21 06:38
I was waiting for some feedback before closing it. Thanks.

**Closed** 2023-08-21 06:38 UTC
Labels: feature-request
